baseURL: "https://m4dh0rs3.github.io/"
title: "Benedikt Schöps"
# copyright: Everything is mine

theme: "PaperMod"
enableEmoji: true

languageCode: en
defaultLanguage: en

languages:
  en:
    languageDirection: en
    languageName: "English"

  de:
    languageDirection: de
    languageName: "De :de:"

    label:
      text: "Über"
      icon: "/android-chrome-192x192.png"

    menu:
      main:
        - name: Archiv
          url: archives
          weight: 40
        - name: Über
          url: menu/resume
          weight: 30
        - name: Beiträge
          url: posts
          weight: 10
        # - name: Showerthoughts
          # url: menu/showerthoughts
          # weight: 20
    
    homeInfoParams:
      title: "Hallo, ich bin Benedikt 👋"
      content: "Das ist meine Webpräsenz: Projekte, Blog, Lebenslauf"

outputs:
  home:
    - HTML
    - RSS
    - JSON
      
markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: Archive
      identifier: archive
      url: archives
      weight: 40
    - name: About
      identifier: resume
      url: menu/resume
      weight: 30
    - name: Posts
      identifier: posts
      url: posts
      weight: 10
    # - name: Showerthoughts
      # identifier: showerthoughts
      # url: menu/showerthoughts
      # weight: 20

params:
  title: "Benedikt Schöps"
  description: "My homepage: Projects, Blog, Resume"
  author: "Benedikt Schöps"

  defaultTheme: light

  env: production

  showReadingTime: true
  showShareButtons: true
  showPostNavLinks: true
  showBreadCrumbs: true

  analytics:
    google:
      siteVerificationTag: "IunKnnqktWMt_-io_r7ydtnQqsdIvPFD9npvF-a-EeM"

    bing:
      siteVerificationTag: "DD2B937F1E4B3638C99C63E6D8148AAE"


  ShowToc: true

  label:
    text: "About"
    icon: "/android-chrome-192x192.png"

  cover:
    linkFullImages: false
    responsiveImages: true

  profileMode:
    enabled: false

  homeInfoParams:
    title: "Hi, I'm Benedikt 👋"
    content: >
      This is my homepage: CV, Projects, Blog

  socialIcons:
    - name: GitHub
      url: "https://github.com/m4dh0rs3"
    - name: Twitter
      url: "https://twitter.com/m4dh0rs3"
    - name: Reddit
      url: "https://reddit.com/u/m4dh0rs3"
    - name: Discord
      url: "https://discord.com/users/2777"
    - name: Email
      url: "mailto:schoeps.benedikt@gmail.com"